/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '404': RouteRecordInfo<'404', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/detail/': RouteRecordInfo<'/detail/', '/detail', Record<never, never>, Record<never, never>>,
    '/detail/more/': RouteRecordInfo<'/detail/more/', '/detail/more', Record<never, never>, Record<never, never>>,
    '/invite/': RouteRecordInfo<'/invite/', '/invite', Record<never, never>, Record<never, never>>,
    '/invite-setting/': RouteRecordInfo<'/invite-setting/', '/invite-setting', Record<never, never>, Record<never, never>>,
    '/rebate-variety/': RouteRecordInfo<'/rebate-variety/', '/rebate-variety', Record<never, never>, Record<never, never>>,
    '/rule/': RouteRecordInfo<'/rule/', '/rule', Record<never, never>, Record<never, never>>,
    '/rule/old': RouteRecordInfo<'/rule/old', '/rule/old', Record<never, never>, Record<never, never>>,
  }
}
